### ISSUE TITLE
Comentar sobre práticas para deixar imagens menores

### ISSUE THREAD

**Issue by Guilhermeslucas** [CommunityBootcamp/Maratona-Kubernetes#1]
Olá, @ErickWendel , tudo bem? Primeiramente, meus parabéns pela maratona, estou gostando muito do material e aprendendo bastante. Notei que no vídeo, você comenta como montar um Dockerfile, usando vários RUNs, o que acaba tornando as imagens um pouco grandinhas. (esse [link](https://www.ianlewis.org/en/creating-smaller-docker-images) fala mais sobre isso). Acha que vale a pena comentar essas questões na maratona, ou não é o foco? Muito obrigado e abraços :)

**Comment by ErickWendel** [comment]
Muito bom! Realmente o objetivo era falar do k8s, mas como trabalhar com imagens e o docker eram pré-requisitos eu pensei em dar aquela pincelada no docker para que os participantes pelo menos conseguirem seguir dali. Eu acho válido, mas acho que não para essa maratona, talvez uma "Maratona Docker", abordando boas práticas conceitos e otimizações seriam bacanas :D 


Muito obrigado pelo feedback!!

**Comment by Guilhermeslucas** [comment]
Entendi! Muito obrigado pela resposta e, novamente, parabéns pelo trabalho!
